/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrecificacaoRouteImport } from './routes/precificacao'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MatrizesLogosRouteImport } from './routes/matrizes-logos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as IndexRouteImport } from './routes/index'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecificacaoRoute = PrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrizesLogosRoute = MatrizesLogosRouteImport.update({
  id: '/matrizes-logos',
  path: '/matrizes-logos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/download': typeof DownloadRoute
  '/estoque': typeof EstoqueRoute
  '/fiscal': typeof FiscalRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/matrizes-logos': typeof MatrizesLogosRoute
  '/pedidos': typeof PedidosRoute
  '/precificacao': typeof PrecificacaoRoute
  '/produtos': typeof ProdutosRoute
  '/tarefas': typeof TarefasRoute
  '/trocar-senha': typeof TrocarSenhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/download': typeof DownloadRoute
  '/estoque': typeof EstoqueRoute
  '/fiscal': typeof FiscalRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/matrizes-logos': typeof MatrizesLogosRoute
  '/pedidos': typeof PedidosRoute
  '/precificacao': typeof PrecificacaoRoute
  '/produtos': typeof ProdutosRoute
  '/tarefas': typeof TarefasRoute
  '/trocar-senha': typeof TrocarSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/download': typeof DownloadRoute
  '/estoque': typeof EstoqueRoute
  '/fiscal': typeof FiscalRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/matrizes-logos': typeof MatrizesLogosRoute
  '/pedidos': typeof PedidosRoute
  '/precificacao': typeof PrecificacaoRoute
  '/produtos': typeof ProdutosRoute
  '/tarefas': typeof TarefasRoute
  '/trocar-senha': typeof TrocarSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/download'
    | '/estoque'
    | '/fiscal'
    | '/fornecedores'
    | '/login'
    | '/matrizes-logos'
    | '/pedidos'
    | '/precificacao'
    | '/produtos'
    | '/tarefas'
    | '/trocar-senha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/download'
    | '/estoque'
    | '/fiscal'
    | '/fornecedores'
    | '/login'
    | '/matrizes-logos'
    | '/pedidos'
    | '/precificacao'
    | '/produtos'
    | '/tarefas'
    | '/trocar-senha'
  id:
    | '__root__'
    | '/'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/download'
    | '/estoque'
    | '/fiscal'
    | '/fornecedores'
    | '/login'
    | '/matrizes-logos'
    | '/pedidos'
    | '/precificacao'
    | '/produtos'
    | '/tarefas'
    | '/trocar-senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaixaRoute: typeof CaixaRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DownloadRoute: typeof DownloadRoute
  EstoqueRoute: typeof EstoqueRoute
  FiscalRoute: typeof FiscalRoute
  FornecedoresRoute: typeof FornecedoresRoute
  LoginRoute: typeof LoginRoute
  MatrizesLogosRoute: typeof MatrizesLogosRoute
  PedidosRoute: typeof PedidosRoute
  PrecificacaoRoute: typeof PrecificacaoRoute
  ProdutosRoute: typeof ProdutosRoute
  TarefasRoute: typeof TarefasRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precificacao': {
      id: '/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof PrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrizes-logos': {
      id: '/matrizes-logos'
      path: '/matrizes-logos'
      fullPath: '/matrizes-logos'
      preLoaderRoute: typeof MatrizesLogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaixaRoute: CaixaRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DownloadRoute: DownloadRoute,
  EstoqueRoute: EstoqueRoute,
  FiscalRoute: FiscalRoute,
  FornecedoresRoute: FornecedoresRoute,
  LoginRoute: LoginRoute,
  MatrizesLogosRoute: MatrizesLogosRoute,
  PedidosRoute: PedidosRoute,
  PrecificacaoRoute: PrecificacaoRoute,
  ProdutosRoute: ProdutosRoute,
  TarefasRoute: TarefasRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
